version: '3'
services:
  redis:
    image: 'redis'
    command: redis-server
    ports:
      - "6379:6379"
  forum-server:
    build: .
    image: 'magicforum'
    ports:
      - "8000:8000"
      - "8443:8443"
